# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS5470 SYSML (Fall 2025)
tagline: Systems for Large-Scale Machine Learning
description: Systems for Large-Scale Machine Learning (Cornell CS5470) — Fall 2025 archive
author: Rachee Singh
baseurl: '/sysml-fa25'

exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.6.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
